# Generated by Django 4.0.4 on 2023-02-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('emai', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('dept', models.CharField(max_length=30)),
                ('addres', models.CharField(max_length=100)),
            ],
        ),
    ]
