# Generated by Django 4.0.4 on 2023-03-02 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_add_hospital_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_hospital_data',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
