# Generated by Django 4.0.4 on 2023-03-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_add_hospital_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_hospital_data',
            name='oxygen',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
