# Generated by Django 4.0.4 on 2023-03-19 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_appointment_rest_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_rest_data',
            name='mail',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
