# Generated by Django 4.0.4 on 2023-03-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_time_appointment_rest_data_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_rest_data',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
