# Generated by Django 4.0.4 on 2023-03-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_appointment_rest_data_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_rest_data',
            name='approved',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
