# Generated by Django 4.0.4 on 2023-03-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_appointment_rest_data_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_rest_data',
            name='desc',
            field=models.CharField(default='No', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='appointment_rest_data',
            name='hospital',
            field=models.CharField(max_length=200),
        ),
    ]
