# Generated by Django 4.0.4 on 2023-03-21 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_appointment_rest_data_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_rest_data',
            name='dept',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
