# Generated by Django 4.0.4 on 2023-03-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_appointment_rest_data_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_rest_data',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointment_rest_data',
            name='time',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
