# Generated by Django 4.0.4 on 2023-03-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_appointment_rest_data_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='medical_remainder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('does', models.CharField(max_length=30)),
                ('no_of_days', models.CharField(max_length=30)),
                ('Remarks', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
