# Generated by Django 4.0.4 on 2023-03-31 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_medical_remainder'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_remainder',
            name='Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medical_remainder',
            name='mail',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
