# Generated by Django 4.0.4 on 2023-04-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_medical_remainder_name_medical_remainder_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='medical_rest_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='medical_remainder',
            name='does',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='medical_remainder',
            name='medicine_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medical_remainder',
            name='no_of_days',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
